<?php
/**
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/** @var $tmpBlock \Manadev\LayeredNavigation\Blocks\Navigation */
/** @var $block \Manadev\LayeredNavigation\Blocks\FilterRenderer */
/** @var $data array */
/** @var $engineFilter \Manadev\LayeredNavigation\EngineFilter */
/** @var $filter \Manadev\LayeredNavigation\Models\Filter */
/** @var $filterTemplate \Manadev\LayeredNavigationCategoryTree\FilterTemplates\Category\AbstractTree */
$filterTemplate = $engineFilter->getFilterTemplate();
?>
<div id="<?php echo $block->getFilterName($filter) ?>" class="mana-parents-children">
<ol class="items mana-parents" data-mage-init='{ "Manadev_LayeredNavigation/js/FilterView": {} }'>
<?php while (count($data) == 1): ?>
    <?php foreach ($data as $item): ?>
        <?php if ($item['count'] > 0 && !$item['is_selected']) : ?>
            <li class="<?php echo $item['is_selected'] ? 'mana-selected' : '' ?> item">
                <a href="<?php echo $block->getReplaceItemUrl($engineFilter, $item) ?>"<?php echo $block->getReplaceItemLinkAttributes($engineFilter, $item) ?>>
                    <?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?>
                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php echo $item['count'] ?></span>
                    <?php endif; ?>
                </a>
            </li>
        <?php else : ?>
            <li class="<?php echo $item['is_selected'] ? 'mana-selected' : '' ?> item">
                <span class="label"><?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?></span>
                <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php echo $item['count'] ?></span>
                <?php endif; ?>
            </li>
        <?php endif; ?>
    <?php endforeach ?>
    <?php $data = $data[0]['children']; ?>
<?php endwhile ?>
</ol>

<ol class="items mana-children" data-mage-init='{ "Manadev_LayeredNavigation/js/FilterView": {} }'>
    <?php foreach ($data as $item): ?>
        <?php if ($item['count'] > 0 && !$item['is_selected']) : ?>
            <li class="<?php echo $item['is_selected'] ? 'mana-selected' : '' ?> item">
                <a href="<?php echo $block->getReplaceItemUrl($engineFilter, $item) ?>"<?php echo $block->getReplaceItemLinkAttributes($engineFilter, $item) ?>>
                    <?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?>
                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php echo $item['count'] ?></span>
                    <?php endif; ?>
                </a>
            </li>
        <?php else : ?>
            <li class="<?php echo $item['is_selected'] ? 'mana-selected' : '' ?> item">
                <span class="label"><?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?></span>
                <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php echo $item['count'] ?></span>
                <?php endif; ?>
            </li>
        <?php endif; ?>
    <?php endforeach ?>
</ol>
</div>