<?php
/**
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/** @var $tmpBlock \Manadev\LayeredNavigation\Blocks\Navigation */
/** @var $block \Manadev\LayeredNavigation\Blocks\FilterRenderer */
/** @var $data array */
/** @var $engineFilter \Manadev\LayeredNavigation\EngineFilter */
/** @var $filter \Manadev\LayeredNavigation\Models\Filter */
/** @var $filterTemplate \Manadev\LayeredNavigationCategoryTree\FilterTemplates\Category\AbstractTree */
$filterTemplate = $engineFilter->getFilterTemplate();
?>
<ul id="<?php echo $block->getFilterName($filter) ?>" class="mana-filter-category-tree"
    data-mage-init='{ "Manadev_LayeredNavigationCategoryTree/js/manadevCategoryTreeFilter": { "default_state": "<?php echo $filterTemplate->isTreeAllExpanded() ? 'expand' : 'collapse' ?>" } }'>
    <?php foreach($data as $item): ?>
        <?php echo $filterTemplate->renderTreeItem($item, $engineFilter, $block); ?>
    <?php endforeach; ?>
</ul>