<?php

/* @var \Manadev\Seo\Blocks\ContentRenderer $block */

/* @var string $value */

/* @var string $route */
/* @var array $params */
/* @var array $query */

/* @var int|null $page */
/* @var string|null $order */
/* @var string|null $dir */
/* @var string|null $mode */
/* @var string|null $show */

/* @var string|null $keyword */

// show default meta title
echo $value;

// Add page number to page title
if ($page > 1) {
    echo " (Page $page)";
}
