<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$target = $block->getTarget();
$label = $block->getLabel();
?>
<top-nav-rfma href="#" class="humb"></top-nav-rfma>
<a href="https://www.murata.com/" target="_blank">Global Website</a> &nbsp;  &nbsp;  &nbsp;  &nbsp;
<a href="https://www.murata.com/about/newsroom/news" target="_blank">News</a> &nbsp;  &nbsp;  &nbsp;  &nbsp;
<a href="https://www.murata.com/ir" target="_blank">Investor Relations</a> &nbsp;  &nbsp;  &nbsp;  &nbsp;
<a href="https://www.murata.com/careers" target="_blank">Careers</a> &nbsp;  &nbsp;  &nbsp;  &nbsp;
<a href="https://www.murata.com/about/company/muratalocations" target="_blank">Contact Us</a>