<?php
/**
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/** @var $block \Manadev\LayeredNavigation\Blocks\FilterRenderer */
/** @var $data array */
/** @var $engineFilter \Manadev\LayeredNavigation\EngineFilter */
/** @var $filter \Manadev\LayeredNavigation\Models\Filter */
?>
<ol id="<?php echo $block->getFilterName($filter) ?>" class="items mana-filter-checkboxes" data-mage-init='{ "Manadev_LayeredNavigationCheckboxes/js/FilterView": {} }'>
    <?php foreach ($data as $item): ?>
        <?php if ($item['is_selected']) : ?>
            <li class="mana-selected item">
                <a class="checked" href="<?php echo $block->getRemoveItemUrl($engineFilter, $item) ?>"<?php echo $block->getRemoveItemLinkAttributes($engineFilter, $item) ?>>
                    <?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?>
                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php echo $item['count'] ?></span>
                    <?php endif; ?>
                </a>
            </li>
        <?php elseif ($item['count'] > 0) : ?>
            <li class="item">
                <a class="unchecked" href="<?php echo $block->getAddItemUrl($engineFilter, $item) ?>"<?php echo $block->getAddItemLinkAttributes($engineFilter, $item) ?>>
                    <?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?>
                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php echo $item['count'] ?></span>
                    <?php endif; ?>
                </a>
            </li>
        <?php else : ?>
            <li class="item">
                <a class="unchecked disabled" href="javascript:void(0)">
                    <?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?>
                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                            <span class="count"><?php echo $item['count'] ?></span>
                    <?php endif; ?>
                </a>
            </li>
        <?php endif; ?>
    <?php endforeach ?>
</ol>
