<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php if ($title): ?>
    <div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
        <h1 class="<?php if($cssClass == '') { ?>page-title<?php } else { ?>product_name<?php } ?>"
            <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
            <?php if ($block->getAddBaseAttributeAria()): ?>
                aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
            <?php endif; ?>>
            <?php
                $titles = explode('| ', $title);
                if(count($titles) > 1) {
                    $title = $titles[0];
                }
            ?>
            <?= /* @escapeNotVerified */ $title ?>
        </h1>
        <?= $block->getChildHtml() ?>
    </div>
<?php endif; ?>
