/* States and Provinces */

function printStateMenu(country) {
	var stateSelect = '';
	if (country == 'United States') {
		stateSelect = '<select name="state" id="state" onChange="document.getElementById(\'stateValue\').innerHTML = this.value;" style="width: 275px"><option> Please Select </option><option value="AL"> Alabama </option><option value="AZ"> Arizona </option><option value="AR"> Arkansas </option><option value="CA"> California </option><option value="CO"> Colorado </option><option value="CT"> Connecticut </option><option value="DE"> Delaware </option><option value="DC"> District Of Columbia </option><option value="FL"> Florida </option><option value="GA"> Georgia </option><option value="ID"> Idaho </option><option value="IL"> Illinois </option><option value="IN"> Indiana </option><option value="IA"> Iowa </option><option value="KS"> Kansas </option><option value="KY"> Kentucky </option><option value="LA"> Louisiana </option><option value="ME"> Maine </option><option value="MD"> Maryland </option><option value="MA"> Massachusetts </option><option value="MI"> Michigan </option><option value="MN"> Minnesota </option><option value="MS"> Mississippi </option><option value="MO"> Missouri </option><option value="MT"> Montana </option><option value="NE"> Nebraska </option><option value="NV"> Nevada </option><option value="NH"> New Hampshire </option><option value="NJ"> New Jersey </option><option value="NM"> New Mexico </option><option value="NY"> New York </option><option value="NC"> North Carolina </option><option value="ND"> North Dakota </option><option value="OH"> Ohio </option><option value="OK"> Oklahoma </option><option value="OR"> Oregon </option><option value="PA"> Pennsylvania </option><option value="PR"> Puerto Rico </option><option value="RI"> Rhode Island </option><option value="SC"> South Carolina </option><option value="SD"> South Dakota </option><option value="TN"> Tennessee </option><option value="TX"> Texas </option><option value="UT"> Utah </option><option value="VT"> Vermont </option><option value="VA"> Virginia </option><option value="WA"> Washington </option><option value="WV"> West Virginia </option><option value="WI"> Wisconsin </option><option value="WY"> Wyoming </option></select>';	
	}
	else if (country == 'Canada') {
		stateSelect = '<select name="state" id="state" onChange="document.getElementById(\'stateValue\').innerHTML = this.value;" style="width: 275px"><option> Please Select </option><option value="AB"> Alberta </option><option value="BC"> British Columbia </option><option value="MB"> Manitoba </option><option value="NB"> New Brunswick </option><option value="NS"> Nova Scotia </option><option value="ON"> Ontario </option><option value="PE"> Prince Edward Island </option><option value="QC"> Quebec </option><option value="SK"> Saskatchewan </option></select>';
	}
		else if (country == 'China') {
		stateSelect = '<select name="state" id="state" onChange="document.getElementById(\'stateValue\').innerHTML = this.value;" style="width: 275px"><option> Please Select </option><option value="Anhui"> Anhui </option><option value="Yunnan"> Yunnan </option><option value="Henan"> Henan </option><option value="Hebei"> Hebei </option><option value="Hainan"> Hainan </option><option value="Gansu"> Gansu </option><option value="Jilin"> Jilin </option><option value="Hunan"> Hunan </option><option value="Hubei"> Hubei </option><option value="Jiangxi"> Jiangxi </option><option value="Jiangsu"> Jiangsu </option><option value="Shanxi"> Shanxi </option><option value="Shandong"> Shandong </option><option value="Sichuan"> Sichuan </option><option value="Chongqing"> Chongqing </option><option value="Shanghai"> Shanghai </option><option value="Qinghai"> Qinghai </option><option value="Tianjin"> Tianjin </option><option value="Fujian"> Fujian </option><option value="Beijing"> Beijing </option><option value="Guangdong"> Guangdong </option><option value="Zhejiang"> Zhejiang </option><option value="Macao"> Macao </option><option value="Sahaliyan"> Sahaliyan </option><option value="Guizhou"> Guizhou </option><option value="Liaoning"> Liaoning </option><option value="Shaanxi"> Shaanxi </option></select>';
	}
	else {
		stateSelect = '<select name="state" id="state" disabled  style="width: 275px"><option value="">State/Province...</option></select>';
		document.getElementById('stateValue').innerHTML = '';
	}
	document.getElementById('stateSelect').innerHTML = stateSelect;
	document.getElementById('countryValue').innerHTML = document.getElementById('country').value;
	document.getElementById('stateValue').innerHTML = document.getElementById('state').value;
}
