<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$target = $block->getTarget();
$label = $block->getLabel();
?>
<!--GA MPS -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-3923220-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-3923220-1');
</script>
<top-nav-rfma href="#" class="humb"></top-nav-rfma>
<a href="https://www.murata.com/" target="_blank">Global Website</a> &nbsp;  &nbsp;  &nbsp;  &nbsp;
<a href="/news/category/news-releases">News</a> &nbsp;  &nbsp;  &nbsp;  &nbsp;
<a href="/about/careers.html">Careers</a> &nbsp;  &nbsp;  &nbsp;  &nbsp;
<a href="https://www.murata.com/en-us/support/contactinformation" target="_blank">Contact Information</a>
