<?php $_productCollection = $this->getProductCollection(); ?>
<div class="category-products-mobile">
    <?php foreach($_productCollection as $product) { ?>
        <div class="category-product-item">
            <div class="category-product-item-option">
                <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($product->getName(), null, true) ?>" class="tablelink_rfm main-link">
                    <?php echo $product->getName(); ?>
                </a>
            </div>
            <?php if($sku = $product->getSku()) { ?>
                <div class="product-option">
                    <span>Order Number:</span>
                    <span class="product-option-value"><?php echo $sku; ?></span>
                </div>
            <?php } ?>
            <?php if($chipset = $product->getRfmChipset()) { ?>
                <div class="product-option">
                    <span>Chipset:</span>
                    <span class="product-option-value">
                        <?php echo $chipset; ?>
                    </span>
                </div>
            <?php } ?>
            <?php if($wlan = $product->getAttributeText('rfm_wlan')) { ?>
                <div class="product-option">
                    <span>WLAN:</span>
                    <span class="product-option-value">
                        <?php echo $wlan; ?>
                    </span>
                </div>
            <?php } ?>
            <?php if($bt = $product->getAttributeText('rfm_bluetooth')) { ?>
                <div class="product-option">
                    <span>BT:</span>
                    <span class="product-option-value"><?php echo $bt; ?></span>
                </div>
            <?php } ?>
            <?php if($clock = $product->getRfmClockSystem()) { ?>
                <div class="product-option">
                    <span>Clock:</span>
                    <span class="product-option-value"><?php echo $clock; ?></span>
                </div>
            <?php } ?>
            <?php if($interface = $product->getRfmHostInterface()) { ?>
                <div class="product-option">
                    <span>Host Interface:</span>
                    <span class="product-option-value">
                        <?php echo $interface; ?>
                    </span>
                </div>
            <?php } ?>
            <?php if($status = $block->wirelessStatuses($product)) { ?>
                <div class="product-option">
                    <?= $status ?>
                </div>
            <?php } ?>
            <?php if ($product->getAttributeText('product_status') != "Obsolete"): ?>
                <div class="product-option">
                    <input title="Add <?php echo $product->getName(); ?> to Compare List" value="<?php echo $product->getId(); ?>" type="checkbox" class="input-checkbox compare-add add"/>
                    <input type="hidden"/>
                </div>
            <?php endif; ?>
        </div>
    <?php } ?>
</div>
<div class="category-products">
    <table width="100%" cellpadding="10px" border="5"
           class="listtable">
        <tr class="listtr">
            <td width="73px" class=listtdtop>Part</td>
            <td width="97px" class=listtdtop>Order Number</td>
            <td width="66px" class=listtdtop>Chipset</td>
            <td width="73px" class=listtdtop>WLAN</td>
            <td width="10px" class=listtdtop>BT</td>
            <td width="10px" class=listtdtop>Clock</td>
            <td width="73px" class=listtdtop>Host Inter-</br>
                face
            </td>
            <td width="33px" class=listtdtop>Dimen</td>
            <td width="23px" class=listtdtop>Cert</td>
            <td width="50px" class=listtdtop>Grade</td>
            <td width="68px" class=listtdtop>Status</td>
            <td width="28px" class=listtdtop>Com-<br/>pare</td>
        </tr>
        <?php foreach ($_productCollection as $product) { ?>
            <tr class="listtr">
                <td width="100px" class=listtd>
                    <a href="<?php echo $product->getProductUrl() ?>"
                       title="<?php echo $this->stripTags($product->getName(), null, true) ?>"
                       class="tablelink_rfm"><?php echo $product->getName(); ?>
                    </a>
                </td>
                <td class=listtd><?php echo $product->getSku(); ?></td>
                <td class=listtd><?php echo $product->getRfmChipset(); ?></td>
                <td class=listtd><?php echo $product->getAttributeText('rfm_wlan'); ?></td>
                <td class=listtd><?php echo $product->getAttributeText('rfm_bluetooth'); ?></td>
                <td class=listtd><?php echo $product->getRfmClockSystem(); ?></td>
                <td class=listtd><?php echo $product->getRfmHostInterface(); ?></td>
                <td class=listtd><?php echo $product->getRfmDimension(); ?></td>
                <td class=listtd><?php echo $product->getAttributeText('rfm_certified_table'); ?></td>
                <td class=listtd>
                    <?php if ($product->getAttributeText('rfm_grade') == 4646) {
                        echo 'Consumer';
                    } else { ?>
                        <?php echo $product->getAttributeText('rfm_grade'); ?>
                    <?php } ?>
                </td>
                <td><?php echo $block->wirelessStatuses($product); ?></td>
                <td class=listtd>
                    <?php if ($product->getAttributeText('product_status') != "Obsolete"): ?>
                        <input title="Add <?php echo $product->getName(); ?> to Compare List"
                               value="<?php echo $product->getId(); ?>" type="checkbox"
                               class="input-checkbox compare-add add"/>
                        <input type="hidden"/>
                    <?php endif; ?>
                </td>
            </tr>
        <?php }; ?>
    </table>
</div>


