<?php $_productCollection = $this->getProductCollection(); ?>
<div class="category-products-mobile">
    <?php foreach($_productCollection as $product) { ?>
        <div class="category-product-item">
            <div class="category-product-item-option">
                <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($product->getName(), null, true) ?>" class="tablelink_rfm main-link">
                    <?php echo $product->getName(); ?>
                </a>
            </div>
            <?php if($freq = $product->getRfmFreq()) { ?>
                <div class="product-option">
                    <span>Frequency:</span>
                    <span class="product-option-value"><?php echo $freq; ?></span>
                </div>
            <?php } ?>
            <?php if($dataRate = $product->getData('rfm_data_rate')) { ?>
                <div class="product-option">
                    <span>Data Rate:</span>
                    <span class="product-option-value">
                        <?php echo rtrim(rtrim($block->escapeHtml($dataRate), '0'), '.') ?>kbps
                    </span>
                </div>
            <?php } ?>
            <?php if($powerRange = $product->getRfmOutputPowerRange()) { ?>
                <div class="product-option">
                    <span>Output Power:</span>
                    <span class="product-option-value"><?php echo $powerRange; ?></span>
                </div>
            <?php } ?>
            <?php if($description = $product->getRfmDescription()) { ?>
                <div class="product-option">
                    <span>Description:</span>
                    <span class="product-option-value"><?php echo $description; ?></span>
                </div>
            <?php } ?>
            <?php if($dimension = $product->getRfmDimension()) { ?>
                <div class="product-option">
                    <span>Dimen.:</span>
                    <span class="product-option-value"><?php echo $dimension; ?></span>
                </div>
            <?php } ?>
            <?php if($productType = $product->getAttributeText('rfm_product_type')) { ?>
                <div class="product-option">
                    <span>Product Type:</span>
                    <span class="product-option-value"><?php echo $productType; ?></span>
                </div>
            <?php } ?>
            <?php if($status = $block->wirelessStatuses($product)) { ?>
                <div class="product-option">
                    <?= $status ?>
                </div>
            <?php } ?>
            <?php if ($product->getAttributeText('product_status') != "Obsolete"): ?>
                <div class="product-option">
                    <input title="Add <?php echo $product->getName(); ?> to Compare List" value="<?php echo $product->getId(); ?>" type="checkbox" class="input-checkbox compare-add add"/>
                    <input type="hidden"/>
                </div>
            <?php endif; ?>
        </div>
    <?php } ?>
</div>
<div class="category-products">
    <table width="100%" cellpadding="10px" border="5" class="listtable">
        <tr class="listtr">
            <td class=listtdtop>Part</td>
            <td class=listtdtop>Frequency</td>
            <td class=listtdtop>Data Rate</td>
            <td class=listtdtop>Output Power</td>
            <td class=listtdtop>Description</td>
            <td class=listtdtop>Dimen.</td>
            <td class=listtdtop>Product Type</td>
            <td class=listtdtop>Status</td>
            <td class=listtdtop>Compare</td>
        </tr>
        <?php $_productCollection = $this->getProductCollection(); ?>
        <?php foreach($_productCollection as $product) { ?>
            <tr class="listtr">
                <td width="100px" class=listtd>
                    <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $block->stripTags($product->getName(), null, true) ?>"
                        class="tablelink_rfm"><?php echo $product->getName(); ?>
                    </a>
                </td>
                <td class=listtd><?php echo $product->getRfmFreq(); ?></td>
                <td class=listtd><?php echo rtrim(rtrim($block->escapeHtml($product->getRfmDataRate()), '0'), '.') ?> kbps</td>
                <td class=listtd><?php echo $product->getRfmOutputPowerRange(); ?></td>
                <td class=listtd><?php echo $product->getRfmDescription(); ?></td>
                <td class=listtd><?php echo $product->getRfmDimension(); ?></td>
                <td class=listtd><?php echo $product->getAttributeText('rfm_product_type'); ?></td>
                <td><?php echo $block->wirelessStatuses($product); ?></td>
                <td class=listtd>
                    <?php if ($product->getAttributeText('product_status') != "Obsolete"): ?>
                        <input title="Add <?php echo $product->getName(); ?> to Compare List" value="<?php echo $product->getId(); ?>" type="checkbox" class="input-checkbox compare-add add"/>
                        <input type="hidden"/>
                    <?php endif; ?>
                </td>
            </tr>
        <?php }; ?>
    </table>
</div>
