<?php $product = $this->getProduct(); ?>
<?php $attributeSetId = $product->getAttributeSetId(); ?>
<?php
if(
    in_array(
        $attributeSetId, [
            Murata\Category\Block\Product\ListProduct::DC_DC_Converters,
            Murata\Category\Block\Product\ListProduct::AC_DC_Power_Supplies,
            Murata\Category\Block\Product\ListProduct::Micro_DC_DC_Converters,
        ]
    )
) { ?>
    <?php echo $block->specTable('dc-ac-micro', $product); ?>
<?php } ?>
<?php if($attributeSetId == Murata\Category\Block\Product\ListProduct::Digital_Panel_Meters) { ?>
    <?php echo $block->specTable('d-panel-meters', $product); ?>
<?php } ?>
<?php if($attributeSetId == Murata\Category\Block\Product\ListProduct::Digital_Panel_Meters_Accessories) { ?>
    <?php echo $block->specTable('d-panel-meters-accessories', $product); ?>
<?php } ?>
<?php if($attributeSetId == Murata\Category\Block\Product\ListProduct::Inductors) { ?>
    <?php echo $block->specTable('inductors', $product); ?>
<?php } ?>
<?php if($attributeSetId == Murata\Category\Block\Product\ListProduct::Pulse_Transformer) { ?>
    <?php echo $block->specTable('pulse-transformer', $product); ?>
<?php } ?>
<?php if($attributeSetId == Murata\Category\Block\Product\ListProduct::Current_Sensing_Transformer) { ?>
    <?php echo $block->specTable('current-sensing-transformer', $product); ?>
<?php } ?>
<?php if($attributeSetId == Murata\Category\Block\Product\ListProduct::Application_Specific_Transformer) { ?>
    <?php echo $block->specTable('app-specific-transformer', $product); ?>
<?php } ?>
<?php if($attributeSetId == Murata\Category\Block\Product\ListProduct::Transformers) { ?>
    <?php echo $block->specTable('transformers', $product); ?>
<?php } ?>
<?php if($attributeSetId == Murata\Category\Block\Product\ListProduct::Common_Mode_Chokes) { ?>
    <?php echo $block->specTable('common-mode-chokes', $product); ?>
<?php } ?>
<?php if($attributeSetId == Murata\Category\Block\Product\ListProduct::Open_Compute) { ?>
    <?php echo $block->specTable('open-compute', $product); ?>
<?php } ?>
