<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div class="top-bar">
    <form role="form" class="form minisearch" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
        <div class="field search form-search">
            <div class="control col-xs-3">
                <input id="search"
                       data-mage-init='{"quickSearch":{
                            "formSelector":"#search_mini_form",
                            "url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
                            "destinationSelector":"#search_autocomplete"}
                       }'
                       type="text"
                       name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
                       value="<?php /* @escapeNotVerified */ if($helper->getEscapedQueryText()) { echo $helper->getEscapedQueryText(); } else { echo $block->getCurrentPlaceholder(); } ?>"
                       class="input-text"
                       maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
                       role="combobox"
                       onfocus="if(this.value == '<?php echo $block->getCurrentPlaceholder(); ?>') { this.value = ''; }"
                       onfocusout="if(this.value == '') { this.value = '<?php echo $block->getCurrentPlaceholder(); ?>'; }"
                       aria-haspopup="false"
                       aria-autocomplete="both"
                       autocomplete="off"/>
                <button type="submit" title="Go" class="button"><span><span></span></span></button>
                <div id="search_autocomplete" class="search-autocomplete"></div>
                <?= $block->getChildHtml() ?>
            </div>
        </div>
        <div class="actions" style="display:none">
            <button type="submit"
                    title=""
                    class="action search">
                <span></span>
            </button>
        </div>
    </form>
    <?php if($block->getStoreId() == $block->wirelessStoreId()) { ?>
        <!--div class="language-switcher">
            <a href="/"><img width="30" height="18" title="English" alt="English" src="/pub/images/en.gif" complete="complete"></a>&nbsp;
            <a href="https://www.murata.com/ja-jp/group/murataelectronics/solutions/power" target="_blank">
                <img width="30" height="18" title="Japanese" alt="Japanese" src="/pub/images/jp.gif" complete="complete">
            </a>&nbsp;
        </div-->
    <?php } ?>
</div>
