<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper  = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_additional = $block->getAdditionalData();
?>
<?php if ($_additional && $_product->getAttributeText('product_status') != Murata\Catalog\Block\Product\View\Attributes::DISCOUNTIED_STATUS): ?>
    <div class="technical-desktop">
        <div class="additional-attributes-wrapper table-wrapper" style="clear: both">
            <ul>
                <li><a href="#"><?= /* @escapeNotVerified */
                        __('Technical Information') ?></a></li>
            </ul>
            <table class="listing">
                <tbody>
                <?php foreach ($_additional as $_data): ?>
                    <?php $dl = $_data['label']; ?>
                    <?php if (
                    !in_array(
                        $dl, [
                        'Data Sheet (pdf)',
                        'Product Status',
                        'Replacement Part',
                        'Location',
                        'Short Description',
                        'Face view',
                        'Face Dim view',
                        'RoHS Exemption 6a',
                        'RoHS Exemption 6c',
                        'RoHS Exemption 7a',
                        'RoHS Exemption 7b',
                        'RoHS Exemption 7c1',
                        'RoHS Exemption 7c2',
                        'RoHS Exemption 7c3',
                        'RoHS Exemption 8',
                        'RoHS Exemption 11b',
                        'RoHS Exemption 34'
                    ]
                    )
                    ) { ?>
                        <?php if ($_helper->productAttribute($_product, $_data['value'], $_data['code']) != 'No') { ?>
                            <tr>
                                <td><?= $block->escapeHtml(__($_data['label'])) ?></td>
                                <td data-th="<?= $block->escapeHtml(__($_data['label'])) ?>">
                                    <?php $value = $_data['value']; ?>
                                    <?php if (strpos($_data['value'], '$') !== false) {
                                        $value = str_replace('.00', '', str_replace('$', '', $value));
                                    } ?>
                                    <?php $value = $_helper->productAttribute($_product, $value, $_data['code']); ?>
                                    <?= /* @escapeNotVerified */
                                    $value; ?>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="technical-mobile">
        <div class="catalog-category-view">
            <div class="item">
                <div class="content_wrap">
                    <div class="main_content2">
                        <div class="list_category">
                            <div class="item">
                                <div class="info product details product-item-details">
                                    <div class="descr_content">
                                        <?php foreach ($_additional as $_data): ?>
                                            <?php $dl = $_data['label']; ?>
                                            <?php if (
                                            !in_array(
                                                $dl, [
                                                    'Data Sheet (pdf)',
                                                    'Product Status',
                                                    'Replacement Part',
                                                    'Location',
                                                    'Short Description',
                                                    'Face view',
                                                    'Face Dim view',
                                                    'RoHS Exemption 6a',
                                                    'RoHS Exemption 6c',
                                                    'RoHS Exemption 7a',
                                                    'RoHS Exemption 7b',
                                                    'RoHS Exemption 7c1',
                                                    'RoHS Exemption 7c2',
                                                    'RoHS Exemption 7c3',
                                                    'RoHS Exemption 8',
                                                    'RoHS Exemption 11b',
                                                    'RoHS Exemption 34'
                                                ]
                                            )
                                            ) { ?>
                                                <?php if ($_helper->productAttribute($_product, $_data['value'], $_data['code']) != 'No') { ?>
                                                    <div class="data">
                                                        <div class="top"><?= $block->escapeHtml(__($_data['label'])) ?></div>
                                                        <div class="bottom">
                                                            <?php $value = $_data['value']; ?>
                                                            <?php if (strpos($_data['value'], '$') !== false) {
                                                                $value = str_replace('.00', '', str_replace('$', '', $value));
                                                            } ?>
                                                            <?php $value = $_helper->productAttribute($_product, $value, $_data['code']); ?>
                                                            <?= /* @escapeNotVerified */
                                                            $value; ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            <?php } ?>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
