<?php
$collection = $block->getLoadedProductCollection(); ?>
<div class="category-products">

    <ol class="products-list" id="products-list">
        <div id="freezehead" name="freezehead">
            <table id="test" width="100%" border="1" class="listtable_eol">
                <tr>
                    <th width="132px" class=listtdtop>Series</th>
                    <th width="294px" class=listtdtop>Optional Details</th>
                    <th width="74px" class=listtdtop>Status</th>
                    <th width="96px" class=listtdtop>Series Type</th>
                    <th width="78px" class=listtdtop>Solidworks®</th>
                    <th width="54px" class=listtdtop>Step</th>
                    <th width="54px" class=listtdtop>Iges</th>
                    <th width="41px" class=listtdtop>3D PDF</th>
                </tr>
            </table>
        </div>
        <table id="test" width="100%" border="1" class="listtable_eol">
            <?php foreach ($collection as $_product): ?>
                <tr>
                    <td width="132px" >
                        <a href="/datasheet?<?php echo $_product->getData('series_datasheet') ?>"><?php echo $_product->getData('name') ?></a>
                    </td>
                    <td width="294px" ><?php echo $_product->getData('series_3d_details') ?></td>
                    <td width="74px" >

                        <?php if ($_product->getAttributeText('series_status') == "Recommended In Production") { ?>
                            <img src="/images/recommended.jpg" alt="Recommended" title="Status Recommended"/><br><img
                                    src="/images/inproduction.jpg" alt="In Production" title="Status In Production"/>
                        <?php } ?>

                        <?php if ($_product->getAttributeText('series_status') == "In Production") { ?>
                            <img src="/images/inproduction.jpg" alt="In Production" title="Status In Production"/>
                        <?php } ?>

                        <?php if ($_product->getAttributeText('series_status') == "In Production/Discontinued") { ?>
                            <img src="/images/inproduction.jpg" alt="In Production" title="Status In Production"/><br>
                            <img src="/images/discontinued.jpg" alt="Discontinued" title="Status Discontinued"/>
                        <?php } ?>

                        <?php if ($_product->getAttributeText('series_status') == "Recommended In Production/Discontinued") { ?>
                            <img src="/images/recommended.jpg" alt="Recommended" title="Status Recommended"/><br><img
                                    src="/images/inproduction.jpg" alt="In Production" title="Status In Production"/>
                            <br><img src="/images/discontinued.jpg" alt="Discontinued" title="Status Discontinued"/>
                        <?php } ?>

                        <?php if ($_product->getAttributeText('series_status') == "In Production/To be Discontinued") { ?>
                            <img src="/images/inproduction.jpg" alt="In Production" title="Status In Production"/><br>
                            <img src="/images/to_be_discontinued.jpg" alt="To Be Discontinued"
                                 title="Status To Be Discontinued"/>
                        <?php } ?>

                        <?php if ($_product->getAttributeText('series_status') == "Recommended In Production/To be Discontinued") { ?>
                            <img src="/images/recommended.jpg" alt="Recommended" title="Status Recommended"/><br><img
                                    src="/images/inproduction.jpg" alt="In Production" title="Status In Production"/>
                            <br><img src="/images/to_be_discontinued.jpg" alt="To Be Discontinued"
                                     title="Status To Be Discontinued"/>
                        <?php } ?>

                        <?php if ($_product->getAttributeText('series_status') == "In Production/To be Discontinued/Discontinued") { ?>
                            <img src="/images/inproduction.jpg" alt="In Production" title="Status In Production"/><br>
                            <img src="/images/to_be_discontinued.jpg" alt="To Be Discontinued"
                                 title="Status To Be Discontinued"/><br><img src="/images/discontinued.jpg"
                                                                             alt="Discontinued"
                                                                             title="Status Discontinued"/>
                        <?php } ?>

                        <?php if ($_product->getAttributeText('series_status') == "Recommended In Production/To be Discontinued/Discontinued") { ?>
                            <img src="/images/recommended.jpg" alt="Recommended" title="Status Recommended"/><br><img
                                    src="/images/inproduction.jpg" alt="In Production" title="Status In Production"/>
                            <br><img src="/images/to_be_discontinued.jpg" alt="To Be Discontinued"
                                     title="Status To Be Discontinued"/><br><img src="/images/discontinued.jpg"
                                                                                 alt="Discontinued"
                                                                                 title="Status Discontinued"/>
                        <?php } ?>

                        <?php if ($_product->getAttributeText('series_status') == "Discontinued") { ?>
                            <img src="/images/discontinued.jpg" alt="Discontinued" title="Status Discontinued"/>
                        <?php } ?>

                        <?php if ($_product->getAttributeText('series_status') == "To be Discontinued") { ?>
                            <img src="/images/to_be_discontinued.jpg" alt="To Be Discontinued"
                                 title="Status To Be Discontinued"/>
                        <?php } ?>

                        <?php if ($_product->getAttributeText('series_status') == "To be Discontinued/Discontinued") { ?>
                            <img src="/images/to_be_discontinued.jpg" alt="To Be Discontinued"
                                 title="Status To Be Discontinued"/><br><img src="/images/discontinued.jpg"
                                                                             alt="Discontinued"
                                                                             title="Status Discontinued"/>
                        <?php } ?>
                    </td>
                    <td width="96px" >
                        <?php echo $_product->getAttributeText('series_type'); ?>
                    </td>
                    <?php if ($_product->getData('series_3d_solidworks') != "Request") { ?>
                        <td width="78px">
                            <a href="/3d-download?<?php echo $_product->getData('series_3d_solidworks') ?>">Download</a>
                        </td>
                    <?php } else { ?>
                        <td width="78px">
                            <a href="/contact-us.html?part=<?php echo $_product->getData('name') ?> Solidworks File">Request</a>
                        </td>
                    <?php }  ?>

                    <?php if ($_product->getData('series_3d_step') != "Request") { ?>
                        <td width="54px">
                            <a href="/3d-download?<?php echo $_product->getData('series_3d_step') ?>">Download</a>
                        </td>
                    <?php } else { ?>
                        <td width="54px">
                            <a href="/contact-us.html?part=<?php echo $_product->getData('name') ?> Step File">Request</a>
                        </td>
                    <?php }  ?>

                    <?php if ($_product->getData('series_3d_iges') != "Request") { ?>
                        <td width="54px">
                            <a href="/3d-download?<?php echo $_product->getData('series_3d_iges') ?>">Download</a>
                        </td>
                    <?php } else { ?>
                        <td width="54px">
                            <a href="/contact-us.html?part=<?php echo $_product->getData('name') ?> Iges File">Request</a>
                        </td>
                    <?php }  ?>

                    <?php if ($_product->getData('series_3d_pdf') != "Request") { ?>
                        <td width="41px">
                            <a href="/datasheet?<?php echo $_product->getData('series_3d_pdf') ?>">View</a>
                        </td>
                    <?php } else { ?>
                        <td width="41px">
                            &nbsp;<!--a href="/contact-us.html?part=<?php echo $_product->getData('name') ?> 3D PDF File">Request</a-->
                        </td>
                    <?php }  ?>
                </tr>
            <?php endforeach; ?>
        </table>

    </ol>


</div>

<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $('li.item a[href*="/products/"]').click(function () {
            window.setTimeout(
                function () {
                    $("#m-wait").show();
                },
                2000);

        });
    });
</script>


<!----Table head freeze--->
<script>

    window.onscroll = function () {
        myFunction()
    };
    var freezeheader = document.getElementById("freezeheader");
    var sticky = test.offsetTop;

    var bodyRect = document.body.getBoundingClientRect(),
        elemRect = test.getBoundingClientRect(),
        stickier = elemRect.top - bodyRect.top;


    function myFunction() {
        if (window.pageYOffset >= sticky || document.documentElement.scrollTop >= stickier) {

            var e = document.getElementById("freezeheader");
            e.setAttribute("id", "freezeheader2");

        } else {

            var e = document.getElementById("freezeheader2");
            e.setAttribute("id", "freezeheader");
        }
    }
</script>






