<div class="wrap_select_main">
    <form name="jumpy">
        <?php $collection = $this->getProducts(); ?>
        <select name="datasheet" size="1" id="product_dropdown_mobile">
            <option value="">Download a Data Sheet (PDF)</option>
            <option value="">---------</option>
            <option value="/application-notes.html">View APPLICATION NOTES</option>
            <option value="">---------</option>
            <option value="/products/discontinued-and-not-recommended.html">View NOT RECOMMENDED</option>
            <option value="/products/discontinued-and-not-recommended.html">View OBSOLETE</option>
            <option value="">---------</option>
            <?php foreach($collection as $product) { ?>
                <option value="/datasheet?<?php echo $product->getSeriesDatasheet() ?>">
                    <?php echo $product->getName() ?>
                </option>
            <?php } ?>
        </select>
    </form>
</div>