<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php if ($block->getCollection()->getSize()): ?>
    <div class="filter_block" data-mage-init='<?= /* @escapeNotVerified */ $block->getWidgetOptionsJson() ?>'>
        <div class="toolbar">
            <div class="pager toolbar-element">
                <?php include ($block->getTemplateFile('Murata_Theme::product/list/toolbar/amount.phtml')) ?>
                <?php include ($block->getTemplateFile('Murata_Theme::product/list/toolbar/limiter.phtml')) ?>
                <?= $block->getPagerHtml() ?>
            </div>
            <div class="sorter toolbar-element">
                <?php include ($block->getTemplateFile('Murata_Theme::product/list/toolbar/compare-status.phtml')) ?>
                <?php if ($block->isExpanded()): ?>
                    <?php include ($block->getTemplateFile('Murata_Theme::product/list/toolbar/sorter.phtml')) ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif ?>
