<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$html = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId(
    'top_footer_'.$storeManager->getStore()->getCode()
)->toHtml();
$block->getRequest()->getRequestUri();
if(
    $storeManager->getStore()->getId() == Murata\Category\Block\Product\ListProduct::MURATAPS_STORE_ID &&
    $block->getRequest()->getRequestUri() == '/'
) {
    echo $html;
} else {
    $htmls = explode('<!--home page only-->', $html);
    if(count($htmls) > 1) {
        echo $htmls[0];
    } else {
        echo $html;
    }
}
?>