<?php $_product = $this->getProduct(); ?>
<?php $attributeSetId = $_product->getAttributeSetId(); ?>
<?php if (!$block->isWirelessConnectivityPlatforms()) { ?>
    <ul class="buttons list2acction">
        <?php if ($this->escapeHtml($_product->getData('data_sheet'))): ?>
            <?php if ($_product->getAttributeText('regional_availability') == "Japan") { ?>
                <script language="Javascript">
                    var geo_location = (geoplugin_countryName());
                    if (geo_location == "Japan") {
                        document.write('<li><a href="/datasheet?<?php echo $this->escapeHtml($_product->getData('data_sheet')) ?>" class="call2acction-btn-list">Datasheet (pdf) <?php echo $_product->getAttributeText('data_sheet') ?></a></li>');
                    }
                </script>
            <?php } else { ?>
            <?php if ($attributeSetId != Murata\Category\Block\Product\ListProduct::Open_Compute) { ?>
                <li>
                    <a href="/datasheet?<?php echo $this->escapeHtml($_product->getData('data_sheet')) ?>"
                       class="call2acction-btn-list">Datasheet
                        (pdf) <?php echo $_product->getAttributeText('data_sheet') ?>
                    </a>
                </li>
            <?php } ?>
            <?php } ?>
        <?php endif; ?>

        <?php if ($attributeSetId == Murata\Category\Block\Product\ListProduct::Open_Compute) { ?>
            <?php if ($_product->getData('data_sheet')) { ?>
                <li>
                    <a href="/datasheet?<?php echo $this->escapeHtml($_product->getData('data_sheet')) ?>"
                       class="call2acction-btn-list">Datasheet
                        (pdf) <?php echo $_product->getAttributeText('data_sheet') ?>
                    </a>
                </li>
            <?php } ?>
            <?php if ($_product->getData('brochure')) { ?>
                <li>
                    <a href="/datasheet?/data/power/<?php echo $this->escapeHtml($_product->getData('brochure')) ?>"
                       class="call2acction-btn-list">Brochure
                        (pdf) <?php echo $_product->getAttributeText('brochure') ?>
                    </a>
                </li>
            <?php } ?>
            <?php if ($_product->getData('product_brief')) { ?>
                <li>
                    <a href="/datasheet?/data/power/<?php echo $this->escapeHtml($_product->getData('product_brief')) ?>"
                       class="call2acction-btn-list">Product Brief
                        (pdf) <?php echo $_product->getAttributeText('product_brief') ?>
                    </a>
                </li>
            <?php } ?>
        <?php } ?>
        <?php if (0 && $attributeSetId != Murata\Category\Block\Product\ListProduct::Open_Compute) { ?>
            <?php if ($_product->getData('data_sheet')) { ?>
                <li>
                    <a href="/datasheet?<?php echo $this->escapeHtml($_product->getData('data_sheet')) ?>"
                       class="call2acction-btn-list">Datasheet
                        (pdf) <?php echo $_product->getAttributeText('data_sheet') ?>
                    </a>
                </li>
            <?php } ?>
            <?php if ($_product->getData('brochure')) { ?>
                <li>
                    <a href="/datasheet?/data/power/<?php echo $this->escapeHtml($_product->getData('brochure')) ?>"
                       class="call2acction-btn-list">Brochure
                        (pdf) <?php echo $_product->getAttributeText('brochure') ?>
                    </a>
                </li>
            <?php } ?>
            <?php if ($_product->getData('product_brief')) { ?>
                <li>
                    <a href="/datasheet?/data/power/<?php echo $this->escapeHtml($_product->getData('product_brief')) ?>"
                       class="call2acction-btn-list">Product Brief
                        (pdf) <?php echo $_product->getAttributeText('product_brief') ?>
                    </a>
                </li>
            <?php } ?>
        <?php } ?>

        <?php if ($_product->getAttributeText('product_status') != "Discontinued") : ?>
            <?php if ($attributeSetId != Murata\Category\Block\Product\ListProduct::Open_Compute) { ?>
                <li>
                    <a href="/products/stock-check.html?parts=<?php echo $this->stripTags($_product->getName(), null, true) ?>"
                       class="call2acction-btn-list">Stock Check (Where to Buy)
                    </a>
                </li>
            <?php } ?>
        <?php endif; ?>
        <?php if($block->isMurataPs()) { ?>
            <li>
            <a href="/contact-us.html?form=Technical&part=<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="call2acction-btn-list">
                    Technical Support</a>
            </li>
        <?php } else { ?>
            <?php if ($_product->getShortDescription() != "hide_buttons"): ?>
                <?php if ($attributeSetId == Murata\Category\Block\Product\ListProduct::Open_Compute) { ?>
                    <li>
                        <a href="/products/contact.html?part=<?php echo $this->stripTags($_product->getName(), null, true) ?>&inquiry=Open+Compute+Please+do+NOT+delete&app=Data Center"
                           class="call2acction-btn-list">Contact Us
                        </a>
                    </li>
                <?php } else { ?>
                    <li>
                        <a href="/products/contact.html?part=<?php echo $this->stripTags($_product->getName(), null, true) ?>"
                           class="call2acction-btn-list">Contact Us
                        </a>
                    </li>
                <?php } ?>
            <?php endif; ?>
        <?php } ?>
        <li>
        <span class="product-item-inner">
                            <span class="product actions product-item-actions">
                                <span data-role="add-to-links"
                                      class="actions-secondary">
                                        <?php $attributeSetId = $_product->getAttributeSetId(); ?>
                                    <?php if ($attributeSetId != Murata\Category\Block\Product\ListProduct::Open_Compute && $_product->getAttributeText('product_status') != "Discontinued") { ?>
                                        <a style="display:none;" href="#"
                                           class="action tocompare"
                                           title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                           aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                           role="button">
                                                <span><?= /* @escapeNotVerified */
                                                    __('Add to Compare') ?></span>
                                            </a>
                                        <div class="compare-check-box">
                                                <label>
                                                    <input title="Add to Compare List" type="checkbox"
                                                           class="input-checkbox compare-add"
                                                           value="<?php echo $_product->getId(); ?>">
                                                    <?= $block->escapeHtml(__('select to compare')) ?>
                                                </label>
                                            </div>
                                    <?php } ?>
                                </span>
                            </span>
                        </span>
        </li>
    </ul>
<?php } ?>
