<?php $product = $this->getProduct(); ?>
<div class="descr_content">
    <?php if ($block->escapeHtml($product->getData('cs_tran_pri_current_rating_a'))) { ?>
        <div class="data">
            <div class="top">Primary Current Rating (A)</div>
            <div class="bottom"><?php echo rtrim(rtrim($block->escapeHtml($product->getData('cs_tran_pri_current_rating_a')), '0'), '.') ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('cs_tran_turn_ratio_pri'))) { ?>
        <div class="data">
            <div class="top">Turns Ratio</div>
            <div class="bottom">
                <?php echo $block->escapeHtml($product->getData('cs_tran_turn_ratio_pri')) ?>:<?php echo $block->escapeHtml($product->getData('cs_tran_turn_ratio_sec')) ?><? if ($block->escapeHtml($product->getData('cs_tran_turn_ratio_sec2'))): ?>:<?php echo $block->escapeHtml($product->getData('cs_tran_turn_ratio_sec2')) ?><? endif ?>
            </div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('cs_tran_height_mm'))) { ?>
        <div class="data">
            <div class="top">Turns Ratio</div>
            <div class="bottom">
                <?php echo rtrim(rtrim($block->escapeHtml($product->getData('cs_tran_height_mm')), '0'), '.') ?>
                x <?php echo rtrim(rtrim($block->escapeHtml($product->getData('cs_tran_width_mm')), '0'), '.') ?>
                x <?php echo rtrim(rtrim($block->escapeHtml($product->getData('cs_tran_depth_mm')), '0'), '.') ?>
            </div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('cs_tran_mounting_option'))) { ?>
        <div class="data">
            <div class="top">Mounting Option</div>
            <div class="bottom"><?php echo $product->getAttributeText('cs_tran_mounting_option') ?></div>
        </div>
    <?php } ?>
    <?php if ($product->getAttributeText('product_status')) { ?>
        <div class="data">
            <div class="top">Status</div>
            <div class="bottom"><?php echo $block->statuses($product); ?></div>
        </div>
    <?php } ?>
</div>