<?php $product = $this->getProduct(); ?>
<div class="descr_content">
    <?php if ($product->getAttributeText('measuring_range')) { ?>
        <div class="data">
            <div class="top">Measuring Range</div>
            <div class="bottom"><?php echo $product->getAttributeText('measuring_range') ?></div>
        </div>
    <?php } ?>
    <?php if ($product->getAttributeText('display_type')) { ?>
        <div class="data">
            <div class="top">Display Type</div>
            <div class="bottom"><?php echo $product->getAttributeText('display_type') ?></div>
        </div>
    <?php } ?>
    <?php if ($product->getAttributeText('color')) { ?>
        <div class="data">
            <div class="top">Color</div>
            <div class="bottom"><?php echo $product->getAttributeText('color') ?></div>
        </div>
    <?php } ?>
    <?php if ($product->getAttributeText('number_of_digit')) { ?>
        <div class="data">
            <div class="top">Number of Digits</div>
            <div class="bottom"><?php echo $product->getAttributeText('number_of_digit') ?></div>
        </div>
    <?php } ?>
    <?php if ($product->getAttributeText('digit_height_inch')) { ?>
        <div class="data">
            <div class="top">Digit Height (inch)</div>
            <div class="bottom"><?php echo $product->getAttributeText('digit_height_inch') ?>"</div>
        </div>
    <?php } ?>
    <?php if ($product->getAttributeText('power_supply_v')) { ?>
        <div class="data">
            <div class="top">Power Supply (V)</div>
            <div class="bottom"><?php echo $product->getAttributeText('power_supply_v') ?>(V)</div>
        </div>
    <?php } ?>
    <?php if ($product->getAttributeText('operating_temperature_range')) { ?>
        <div class="data">
            <div class="top">Operating Temp. Range (C)</div>
            <div class="bottom"><?php echo $product->getAttributeText('operating_temperature_range') ?></div>
        </div>
    <?php } ?>
    <?php if ($product->getAttributeText('product_status')) { ?>
        <div class="data">
            <div class="top">Status</div>
            <div class="bottom"><?php echo $block->statuses($product); ?></div>
        </div>
    <?php } ?>
</div>