<?php $product = $this->getProduct(); ?>
<div class="descr_content">
    <?php if ($block->escapeHtml($product->getData('inductors_inductance_nom_muh'))) { ?>
        <div class="data">
            <div class="top">Inductance Nom. (&micro;H)</div>
            <div class="bottom"><?php echo rtrim(rtrim($block->escapeHtml($product->getData('inductors_inductance_nom_muh')), '0'), '.') ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('inductors_dc_current_max_a'))) { ?>
        <div class="data">
            <div class="top">DC Current Max. (A)</div>
            <div class="bottom"><?php echo rtrim(rtrim($block->escapeHtml($product->getData('inductors_dc_current_max_a')), '0'), '.') ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('inductors_saturated_current_a'))) { ?>
        <div class="data">
            <div class="top">Saturation Current (A)</div>
            <div class="bottom"><?php echo $block->escapeHtml($product->getData('inductors_saturated_current_a')) ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('inductors_dc_resist_max_mom'))) { ?>
        <div class="data">
            <div class="top">DC Resistance Max. (m&Omega;)</div>
            <div class="bottom"><?php echo $block->escapeHtml($product->getData('inductors_dc_resist_max_mom')) ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('inductors_height_mm'))) { ?>
        <div class="data">
            <div class="top">Dimensions H x W x D (mm)</div>
            <div class="bottom">
                <?php echo rtrim(rtrim($block->escapeHtml($product->getData('inductors_height_mm')), '0'), '.') ?>
                x <?php echo rtrim(rtrim($block->escapeHtml($product->getData('inductors_width_mm')), '0'), '.') ?>
                x <?php echo rtrim(rtrim($block->escapeHtml($product->getData('inductors_depth_mm')), '0'), '.') ?>
                <td>
            </div>
        </div>
    <?php } ?>
    <?php if ($product->getAttributeText('product_status') || $product->getAttributeText('rfm_product_status')) { ?>
        <div class="data">
            <div class="top">Status</div>
            <div class="bottom"><?php echo $block->statuses($product); ?></div>
        </div>
    <?php } ?>
</div>