<?php $product = $this->getProduct(); ?>
<div class="descr_content">
    <?php if ($block->escapeHtml($product->getData('dc_current_max'))) { ?>
        <div class="data">
            <div class="top">DC Current Max</div>
            <div class="bottom"><?php echo $product->getAttributeText('dc_current_max') ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('dc_resistance_secondary_max'))) { ?>
        <div class="data">
            <div class="top">DC Resistance Secondary Max</div>
            <div class="bottom"><?php echo $product->getAttributeText('dc_resistance_secondary_max') ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('isolation_voltage'))) { ?>
        <div class="data">
            <div class="top">Isolation Voltage</div>
            <div class="bottom"><?php echo $product->getAttributeText('isolation_voltage') ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('max_leakage_inductance'))) { ?>
        <div class="data">
            <div class="top">Leakage Inductance Max</div>
            <div class="bottom"><?php echo $product->getAttributeText('max_leakage_inductance') ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('primary_inductance_typical'))) { ?>
        <div class="data">
            <div class="top">Primary Inductance Typical</div>
            <div class="bottom"><?php echo $product->getAttributeText('primary_inductance_typical') ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('turn_ratio'))) { ?>
        <div class="data">
            <div class="top">Turn Ratio</div>
            <div class="bottom"><?php echo $product->getAttributeText('turn_ratio') ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('volt_time_product'))) { ?>
        <div class="data">
            <div class="top">Volt Time Product</div>
            <div class="bottom"><?php echo $product->getAttributeText('volt_time_product') ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('volt_time_product'))) { ?>
        <div class="data">
            <div class="top">Volt Time Product</div>
            <div class="bottom"><?php echo $product->getAttributeText('volt_time_product') ?></div>
        </div>
    <?php } ?>
    <?php if ($block->escapeHtml($product->getData('form_factor'))) { ?>
        <div class="data">
            <div class="top">Form Factor</div>
            <div class="bottom"><?php echo $product->getAttributeText('form_factor') ?></div>
        </div>
    <?php } ?>
    <?php if ($product->getAttributeText('product_status')) { ?>
        <div class="data">
            <div class="top">Status</div>
            <div class="bottom"><?php echo $block->statuses($product); ?></div>
        </div>
    <?php } ?>
</div>